### ISSUE TITLE
Hawaii data file mislabeled 

### ISSUE THREAD

**Issue by nvkelso** [aaron-strauss/precinct-shapefiles#10]
Excellent project!

I was confused by the following file:

- https://github.com/aaron-strauss/precinct-shapefiles/blob/master/hi/2012_fl_precincts.zip

It's name says `fl` but in fact opening it up does show Hawaii data. Suggest changing the file name to:

- 2012_hawaii_precincts.zip

**Comment by aaron-strauss** [comment]
Thanks!
